use  PBL3_Database

select * from Phuong_Xa

INSERT INTO Quan_Huyen VALUES(101, 1, N'Huyện An Phú')
INSERT INTO Quan_Huyen VALUES(102, 1, N'Huyện Châu Phú')
INSERT INTO Quan_Huyen VALUES(103, 1, N'Huyện Châu Thành')
INSERT INTO Quan_Huyen VALUES(104, 1, N'Huyện Chợ Mới')
INSERT INTO Quan_Huyen VALUES(105, 1, N'Huyện Phú Tân')
INSERT INTO Quan_Huyen VALUES(106, 1, N'Huyện Thoại Sơn')
INSERT INTO Quan_Huyen VALUES(107, 1, N'Huyện Tri Tôn')
INSERT INTO Quan_Huyen VALUES(108, 1, N'Thành phố Châu Đốc')
INSERT INTO Quan_Huyen VALUES(109, 1, N'Thành phố Long Xuyên')
INSERT INTO Quan_Huyen VALUES(110, 1, N'Thị xã Tân Châu')
INSERT INTO Quan_Huyen VALUES(111, 1, N'Thị xã Tịnh Biên')
INSERT INTO Quan_Huyen VALUES(201, 2, N'Huyện Châu Đức')
INSERT INTO Quan_Huyen VALUES(202, 2, N'Huyện Côn Đảo')
INSERT INTO Quan_Huyen VALUES(203, 2, N'Huyện Đất Đỏ')
INSERT INTO Quan_Huyen VALUES(204, 2, N'Huyện Long Điền')
INSERT INTO Quan_Huyen VALUES(205, 2, N'Huyện Xuyên Mộc')
INSERT INTO Quan_Huyen VALUES(206, 2, N'Thành phố Bà Rịa')
INSERT INTO Quan_Huyen VALUES(207, 2, N'Thành phố Vũng Tàu')
INSERT INTO Quan_Huyen VALUES(208, 2, N'Thị xã Phú Mỹ')
INSERT INTO Quan_Huyen VALUES(301, 3, N'Huyện Hiệp Hòa')
INSERT INTO Quan_Huyen VALUES(302, 3, N'Huyện Lạng Giang')
INSERT INTO Quan_Huyen VALUES(303, 3, N'Huyện Lục Nam')
INSERT INTO Quan_Huyen VALUES(304, 3, N'Huyện Lục Ngạn')
INSERT INTO Quan_Huyen VALUES(305, 3, N'Huyện Sơn Động')
INSERT INTO Quan_Huyen VALUES(306, 3, N'Huyện Tân Yên')
INSERT INTO Quan_Huyen VALUES(307, 3, N'Huyện Việt Yên')
INSERT INTO Quan_Huyen VALUES(308, 3, N'Huyện Yên Dũng')
INSERT INTO Quan_Huyen VALUES(309, 3, N'Huyện Yên Thế')
INSERT INTO Quan_Huyen VALUES(310, 3, N'Thành phố Bắc Giang')
INSERT INTO Quan_Huyen VALUES(401, 4, N'Huyện Ba Bể')
INSERT INTO Quan_Huyen VALUES(402, 4, N'Huyện Bạch Thông')
INSERT INTO Quan_Huyen VALUES(403, 4, N'Huyện Chợ Đồn')
INSERT INTO Quan_Huyen VALUES(404, 4, N'Huyện Chợ Mới')
INSERT INTO Quan_Huyen VALUES(405, 4, N'Huyện Na Rì')
INSERT INTO Quan_Huyen VALUES(406, 4, N'Huyện Ngân Sơn')
INSERT INTO Quan_Huyen VALUES(407, 4, N'Huyện Pác Nặm')
INSERT INTO Quan_Huyen VALUES(408, 4, N'Thành Phố Bắc Kạn')
INSERT INTO Quan_Huyen VALUES(501, 5, N'Huyện Đông Hải')
INSERT INTO Quan_Huyen VALUES(502, 5, N'Huyện Hoà Bình')
INSERT INTO Quan_Huyen VALUES(503, 5, N'Huyện Hồng Dân')
INSERT INTO Quan_Huyen VALUES(504, 5, N'Huyện Phước Long')
INSERT INTO Quan_Huyen VALUES(505, 5, N'Huyện Vĩnh Lợi')
INSERT INTO Quan_Huyen VALUES(506, 5, N'Thành phố Bạc Liêu')
INSERT INTO Quan_Huyen VALUES(507, 5, N'Thị xã Giá Rai')
INSERT INTO Quan_Huyen VALUES(601, 6, N'Huyện Gia Bình')
INSERT INTO Quan_Huyen VALUES(602, 6, N'Huyện Lương Tài')
INSERT INTO Quan_Huyen VALUES(603, 6, N'Huyện Tiên Du')
INSERT INTO Quan_Huyen VALUES(604, 6, N'Huyện Yên Phong')
INSERT INTO Quan_Huyen VALUES(605, 6, N'Thành phố Bắc Ninh')
INSERT INTO Quan_Huyen VALUES(606, 6, N'Thành phố Từ Sơn')
INSERT INTO Quan_Huyen VALUES(607, 6, N'Thị xã Quế Võ')
INSERT INTO Quan_Huyen VALUES(608, 6, N'Thị xã Thuận Thành')
INSERT INTO Quan_Huyen VALUES(701, 7, N'Huyện Ba Tri')
INSERT INTO Quan_Huyen VALUES(702, 7, N'Huyện Bình Đại')
INSERT INTO Quan_Huyen VALUES(703, 7, N'Huyện Châu Thành')
INSERT INTO Quan_Huyen VALUES(704, 7, N'Huyện Chợ Lách')
INSERT INTO Quan_Huyen VALUES(705, 7, N'Huyện Giồng Trôm')
INSERT INTO Quan_Huyen VALUES(706, 7, N'Huyện Mỏ Cày Bắc')
INSERT INTO Quan_Huyen VALUES(707, 7, N'Huyện Mỏ Cày Nam')
INSERT INTO Quan_Huyen VALUES(708, 7, N'Huyện Thạnh Phú')
INSERT INTO Quan_Huyen VALUES(709, 7, N'Thành phố Bến Tre')
INSERT INTO Quan_Huyen VALUES(801, 8, N'Huyện An Lão')
INSERT INTO Quan_Huyen VALUES(802, 8, N'Huyện Hoài Ân')
INSERT INTO Quan_Huyen VALUES(803, 8, N'Huyện Phù Cát')
INSERT INTO Quan_Huyen VALUES(804, 8, N'Huyện Phù Mỹ')
INSERT INTO Quan_Huyen VALUES(805, 8, N'Huyện Tây Sơn')
INSERT INTO Quan_Huyen VALUES(806, 8, N'Huyện Tuy Phước')
INSERT INTO Quan_Huyen VALUES(807, 8, N'Huyện Vân Canh')
INSERT INTO Quan_Huyen VALUES(808, 8, N'Huyện Vĩnh Thạnh')
INSERT INTO Quan_Huyen VALUES(809, 8, N'Thành phố Quy Nhơn')
INSERT INTO Quan_Huyen VALUES(810, 8, N'Thị xã An Nhơn')
INSERT INTO Quan_Huyen VALUES(811, 8, N'Thị xã Hoài Nhơn')
INSERT INTO Quan_Huyen VALUES(901, 9, N'Huyện Bắc Tân Uyên')
INSERT INTO Quan_Huyen VALUES(902, 9, N'Huyện Bàu Bàng')
INSERT INTO Quan_Huyen VALUES(903, 9, N'Huyện Dầu Tiếng')
INSERT INTO Quan_Huyen VALUES(904, 9, N'Huyện Phú Giáo')
INSERT INTO Quan_Huyen VALUES(905, 9, N'Thành phố Dĩ An')
INSERT INTO Quan_Huyen VALUES(906, 9, N'Thành phố Tân Uyên')
INSERT INTO Quan_Huyen VALUES(907, 9, N'Thành phố Thủ Dầu Một')
INSERT INTO Quan_Huyen VALUES(908, 9, N'Thành phố Thuận An')
INSERT INTO Quan_Huyen VALUES(909, 9, N'Thị xã Bến Cát')
INSERT INTO Quan_Huyen VALUES(1001, 10, N'Huyện Bù Đăng')
INSERT INTO Quan_Huyen VALUES(1002, 10, N'Huyện Bù Đốp')
INSERT INTO Quan_Huyen VALUES(1003, 10, N'Huyện Bù Gia Mập')
INSERT INTO Quan_Huyen VALUES(1004, 10, N'Huyện Đồng Phú')
INSERT INTO Quan_Huyen VALUES(1005, 10, N'Huyện Hớn Quản')
INSERT INTO Quan_Huyen VALUES(1006, 10, N'Huyện Lộc Ninh')
INSERT INTO Quan_Huyen VALUES(1007, 10, N'Huyện Phú Riềng')
INSERT INTO Quan_Huyen VALUES(1008, 10, N'Thành phố Đồng Xoài')
INSERT INTO Quan_Huyen VALUES(1009, 10, N'Thị xã Bình Long')
INSERT INTO Quan_Huyen VALUES(1010, 10, N'Thị xã Chơn Thành')
INSERT INTO Quan_Huyen VALUES(1011, 10, N'Thị xã Phước Long')
INSERT INTO Quan_Huyen VALUES(1101, 11, N'Huyện Bắc Bình')
INSERT INTO Quan_Huyen VALUES(1102, 11, N'Huyện Đức Linh')
INSERT INTO Quan_Huyen VALUES(1103, 11, N'Huyện Hàm Tân')
INSERT INTO Quan_Huyen VALUES(1104, 11, N'Huyện Hàm Thuận Bắc')
INSERT INTO Quan_Huyen VALUES(1105, 11, N'Huyện Hàm Thuận Nam')
INSERT INTO Quan_Huyen VALUES(1106, 11, N'Huyện Phú Quí')
INSERT INTO Quan_Huyen VALUES(1107, 11, N'Huyện Tánh Linh')
INSERT INTO Quan_Huyen VALUES(1108, 11, N'Huyện Tuy Phong')
INSERT INTO Quan_Huyen VALUES(1109, 11, N'Thành phố Phan Thiết')
INSERT INTO Quan_Huyen VALUES(1110, 11, N'Thị xã La Gi')
INSERT INTO Quan_Huyen VALUES(1201, 12, N'Huyện Cái Nước')
INSERT INTO Quan_Huyen VALUES(1202, 12, N'Huyện Đầm Dơi')
INSERT INTO Quan_Huyen VALUES(1203, 12, N'Huyện Năm Căn')
INSERT INTO Quan_Huyen VALUES(1204, 12, N'Huyện Ngọc Hiển')
INSERT INTO Quan_Huyen VALUES(1205, 12, N'Huyện Phú Tân')
INSERT INTO Quan_Huyen VALUES(1206, 12, N'Huyện Thới Bình')
INSERT INTO Quan_Huyen VALUES(1207, 12, N'Huyện Trần Văn Thời')
INSERT INTO Quan_Huyen VALUES(1208, 12, N'Huyện U Minh')
INSERT INTO Quan_Huyen VALUES(1209, 12, N'Thành phố Cà Mau')
INSERT INTO Quan_Huyen VALUES(1301, 13, N'Huyện Cờ Đỏ')
INSERT INTO Quan_Huyen VALUES(1302, 13, N'Huyện Phong Điền')
INSERT INTO Quan_Huyen VALUES(1303, 13, N'Huyện Thới Lai')
INSERT INTO Quan_Huyen VALUES(1304, 13, N'Huyện Vĩnh Thạnh')
INSERT INTO Quan_Huyen VALUES(1305, 13, N'Quận Bình Thuỷ')
INSERT INTO Quan_Huyen VALUES(1306, 13, N'Quận Cái Răng')
INSERT INTO Quan_Huyen VALUES(1307, 13, N'Quận Ninh Kiều')
INSERT INTO Quan_Huyen VALUES(1308, 13, N'Quận Ô Môn')
INSERT INTO Quan_Huyen VALUES(1309, 13, N'Quận Thốt Nốt')
INSERT INTO Quan_Huyen VALUES(1401, 14, N'Huyện Bảo Lạc')
INSERT INTO Quan_Huyen VALUES(1402, 14, N'Huyện Bảo Lâm')
INSERT INTO Quan_Huyen VALUES(1403, 14, N'Huyện Hạ Lang')
INSERT INTO Quan_Huyen VALUES(1404, 14, N'Huyện Hà Quảng')
INSERT INTO Quan_Huyen VALUES(1405, 14, N'Huyện Hoà An')
INSERT INTO Quan_Huyen VALUES(1406, 14, N'Huyện Nguyên Bình')
INSERT INTO Quan_Huyen VALUES(1407, 14, N'Huyện Quảng Hòa')
INSERT INTO Quan_Huyen VALUES(1408, 14, N'Huyện Thạch An')
INSERT INTO Quan_Huyen VALUES(1409, 14, N'Huyện Trùng Khánh')
INSERT INTO Quan_Huyen VALUES(1410, 14, N'Thành phố Cao Bằng')
INSERT INTO Quan_Huyen VALUES(1501, 15, N'Huyện Hòa Vang')
INSERT INTO Quan_Huyen VALUES(1502, 15, N'Huyện Hoàng Sa')
INSERT INTO Quan_Huyen VALUES(1503, 15, N'Quận Cẩm Lệ')
INSERT INTO Quan_Huyen VALUES(1504, 15, N'Quận Hải Châu')
INSERT INTO Quan_Huyen VALUES(1505, 15, N'Quận Liên Chiểu')
INSERT INTO Quan_Huyen VALUES(1506, 15, N'Quận Ngũ Hành Sơn')
INSERT INTO Quan_Huyen VALUES(1507, 15, N'Quận Sơn Trà')
INSERT INTO Quan_Huyen VALUES(1508, 15, N'Quận Thanh Khê')
INSERT INTO Quan_Huyen VALUES(1601, 16, N'Huyện Buôn Đôn')
INSERT INTO Quan_Huyen VALUES(1602, 16, N'Huyện Cư Kuin')
INSERT INTO Quan_Huyen VALUES(1603, 16, N'Huyện Cư M.gar')
INSERT INTO Quan_Huyen VALUES(1604, 16, N'Huyện Ea H.leo')
INSERT INTO Quan_Huyen VALUES(1605, 16, N'Huyện Ea Kar')
INSERT INTO Quan_Huyen VALUES(1606, 16, N'Huyện Ea Súp')
INSERT INTO Quan_Huyen VALUES(1607, 16, N'Huyện Krông A Na')
INSERT INTO Quan_Huyen VALUES(1608, 16, N'Huyện Krông Bông')
INSERT INTO Quan_Huyen VALUES(1609, 16, N'Huyện Krông Búk')
INSERT INTO Quan_Huyen VALUES(1610, 16, N'Huyện Krông Năng')
INSERT INTO Quan_Huyen VALUES(1611, 16, N'Huyện Krông Pắc')
INSERT INTO Quan_Huyen VALUES(1612, 16, N'Huyện Lắk')
INSERT INTO Quan_Huyen VALUES(1613, 16, N'Huyện M.Đrắk')
INSERT INTO Quan_Huyen VALUES(1614, 16, N'Thành phố Buôn Ma Thuột')
INSERT INTO Quan_Huyen VALUES(1615, 16, N'Thị Xã Buôn Hồ')
INSERT INTO Quan_Huyen VALUES(1701, 17, N'Huyện Cư Jút')
INSERT INTO Quan_Huyen VALUES(1702, 17, N'Huyện Đăk Glong')
INSERT INTO Quan_Huyen VALUES(1703, 17, N'Huyện Đắk Mil')
INSERT INTO Quan_Huyen VALUES(1704, 17, N'Huyện Đắk R.Lấp')
INSERT INTO Quan_Huyen VALUES(1705, 17, N'Huyện Đắk Song')
INSERT INTO Quan_Huyen VALUES(1706, 17, N'Huyện Krông Nô')
INSERT INTO Quan_Huyen VALUES(1707, 17, N'Huyện Tuy Đức')
INSERT INTO Quan_Huyen VALUES(1708, 17, N'Thành phố Gia Nghĩa')
INSERT INTO Quan_Huyen VALUES(1801, 18, N'Huyện Điện Biên')
INSERT INTO Quan_Huyen VALUES(1802, 18, N'Huyện Điện Biên Đông')
INSERT INTO Quan_Huyen VALUES(1803, 18, N'Huyện Mường Ảng')
INSERT INTO Quan_Huyen VALUES(1804, 18, N'Huyện Mường Chà')
INSERT INTO Quan_Huyen VALUES(1805, 18, N'Huyện Mường Nhé')
INSERT INTO Quan_Huyen VALUES(1806, 18, N'Huyện Nậm Pồ')
INSERT INTO Quan_Huyen VALUES(1807, 18, N'Huyện Tủa Chùa')
INSERT INTO Quan_Huyen VALUES(1808, 18, N'Huyện Tuần Giáo')
INSERT INTO Quan_Huyen VALUES(1809, 18, N'Thành phố Điện Biên Phủ')
INSERT INTO Quan_Huyen VALUES(1810, 18, N'Thị Xã Mường Lay')
INSERT INTO Quan_Huyen VALUES(1901, 19, N'Huyện Cẩm Mỹ')
INSERT INTO Quan_Huyen VALUES(1902, 19, N'Huyện Định Quán')
INSERT INTO Quan_Huyen VALUES(1903, 19, N'Huyện Long Thành')
INSERT INTO Quan_Huyen VALUES(1904, 19, N'Huyện Nhơn Trạch')
INSERT INTO Quan_Huyen VALUES(1905, 19, N'Huyện Tân Phú')
INSERT INTO Quan_Huyen VALUES(1906, 19, N'Huyện Thống Nhất')
INSERT INTO Quan_Huyen VALUES(1907, 19, N'Huyện Trảng Bom')
INSERT INTO Quan_Huyen VALUES(1908, 19, N'Huyện Vĩnh Cửu')
INSERT INTO Quan_Huyen VALUES(1909, 19, N'Huyện Xuân Lộc')
INSERT INTO Quan_Huyen VALUES(1910, 19, N'Thành phố Biên Hòa')
INSERT INTO Quan_Huyen VALUES(1911, 19, N'Thành phố Long Khánh')
INSERT INTO Quan_Huyen VALUES(2001, 20, N'Huyện Cao Lãnh')
INSERT INTO Quan_Huyen VALUES(2002, 20, N'Huyện Châu Thành')
INSERT INTO Quan_Huyen VALUES(2003, 20, N'Huyện Hồng Ngự')
INSERT INTO Quan_Huyen VALUES(2004, 20, N'Huyện Lai Vung')
INSERT INTO Quan_Huyen VALUES(2005, 20, N'Huyện Lấp Vò')
INSERT INTO Quan_Huyen VALUES(2006, 20, N'Huyện Tam Nông')
INSERT INTO Quan_Huyen VALUES(2007, 20, N'Huyện Tân Hồng')
INSERT INTO Quan_Huyen VALUES(2008, 20, N'Huyện Thanh Bình')
INSERT INTO Quan_Huyen VALUES(2009, 20, N'Huyện Tháp Mười')
INSERT INTO Quan_Huyen VALUES(2010, 20, N'Thành phố Cao Lãnh')
INSERT INTO Quan_Huyen VALUES(2011, 20, N'Thành phố Hồng Ngự')
INSERT INTO Quan_Huyen VALUES(2012, 20, N'Thành phố Sa Đéc')
INSERT INTO Quan_Huyen VALUES(2101, 21, N'Huyện Chư Păh')
INSERT INTO Quan_Huyen VALUES(2102, 21, N'Huyện Chư Prông')
INSERT INTO Quan_Huyen VALUES(2103, 21, N'Huyện Chư Pưh')
INSERT INTO Quan_Huyen VALUES(2104, 21, N'Huyện Chư Sê')
INSERT INTO Quan_Huyen VALUES(2105, 21, N'Huyện Đăk Đoa')
INSERT INTO Quan_Huyen VALUES(2106, 21, N'Huyện Đăk Pơ')
INSERT INTO Quan_Huyen VALUES(2107, 21, N'Huyện Đức Cơ')
INSERT INTO Quan_Huyen VALUES(2108, 21, N'Huyện Ia Grai')
INSERT INTO Quan_Huyen VALUES(2109, 21, N'Huyện Ia Pa')
INSERT INTO Quan_Huyen VALUES(2110, 21, N'Huyện KBang')
INSERT INTO Quan_Huyen VALUES(2111, 21, N'Huyện Kông Chro')
INSERT INTO Quan_Huyen VALUES(2112, 21, N'Huyện Krông Pa')
INSERT INTO Quan_Huyen VALUES(2113, 21, N'Huyện Mang Yang')
INSERT INTO Quan_Huyen VALUES(2114, 21, N'Huyện Phú Thiện')
INSERT INTO Quan_Huyen VALUES(2115, 21, N'Thành phố Pleiku')
INSERT INTO Quan_Huyen VALUES(2116, 21, N'Thị xã An Khê')
INSERT INTO Quan_Huyen VALUES(2117, 21, N'Thị xã Ayun Pa')
INSERT INTO Quan_Huyen VALUES(2201, 22, N'Huyện Bắc Mê')
INSERT INTO Quan_Huyen VALUES(2202, 22, N'Huyện Bắc Quang')
INSERT INTO Quan_Huyen VALUES(2203, 22, N'Huyện Đồng Văn')
INSERT INTO Quan_Huyen VALUES(2204, 22, N'Huyện Hoàng Su Phì')
INSERT INTO Quan_Huyen VALUES(2205, 22, N'Huyện Mèo Vạc')
INSERT INTO Quan_Huyen VALUES(2206, 22, N'Huyện Quản Bạ')
INSERT INTO Quan_Huyen VALUES(2207, 22, N'Huyện Quang Bình')
INSERT INTO Quan_Huyen VALUES(2208, 22, N'Huyện Vị Xuyên')
INSERT INTO Quan_Huyen VALUES(2209, 22, N'Huyện Xín Mần')
INSERT INTO Quan_Huyen VALUES(2210, 22, N'Huyện Yên Minh')
INSERT INTO Quan_Huyen VALUES(2211, 22, N'Thành phố Hà Giang')
INSERT INTO Quan_Huyen VALUES(2301, 23, N'Huyện Bình Lục')
INSERT INTO Quan_Huyen VALUES(2302, 23, N'Huyện Kim Bảng')
INSERT INTO Quan_Huyen VALUES(2303, 23, N'Huyện Lý Nhân')
INSERT INTO Quan_Huyen VALUES(2304, 23, N'Huyện Thanh Liêm')
INSERT INTO Quan_Huyen VALUES(2305, 23, N'Thành phố Phủ Lý')
INSERT INTO Quan_Huyen VALUES(2306, 23, N'Thị xã Duy Tiên')
INSERT INTO Quan_Huyen VALUES(2401, 24, N'Huyện Ba Vì')
INSERT INTO Quan_Huyen VALUES(2402, 24, N'Huyện Chương Mỹ')
INSERT INTO Quan_Huyen VALUES(2403, 24, N'Huyện Đan Phượng')
INSERT INTO Quan_Huyen VALUES(2404, 24, N'Huyện Đông Anh')
INSERT INTO Quan_Huyen VALUES(2405, 24, N'Huyện Gia Lâm')
INSERT INTO Quan_Huyen VALUES(2406, 24, N'Huyện Hoài Đức')
INSERT INTO Quan_Huyen VALUES(2407, 24, N'Huyện Mê Linh')
INSERT INTO Quan_Huyen VALUES(2408, 24, N'Huyện Mỹ Đức')
INSERT INTO Quan_Huyen VALUES(2409, 24, N'Huyện Phú Xuyên')
INSERT INTO Quan_Huyen VALUES(2410, 24, N'Huyện Phúc Thọ')
INSERT INTO Quan_Huyen VALUES(2411, 24, N'Huyện Quốc Oai')
INSERT INTO Quan_Huyen VALUES(2412, 24, N'Huyện Sóc Sơn')
INSERT INTO Quan_Huyen VALUES(2413, 24, N'Huyện Thạch Thất')
INSERT INTO Quan_Huyen VALUES(2414, 24, N'Huyện Thanh Oai')
INSERT INTO Quan_Huyen VALUES(2415, 24, N'Huyện Thanh Trì')
INSERT INTO Quan_Huyen VALUES(2416, 24, N'Huyện Thường Tín')
INSERT INTO Quan_Huyen VALUES(2417, 24, N'Huyện Ứng Hòa')
INSERT INTO Quan_Huyen VALUES(2418, 24, N'Quận Ba Đình')
INSERT INTO Quan_Huyen VALUES(2419, 24, N'Quận Bắc Từ Liêm')
INSERT INTO Quan_Huyen VALUES(2420, 24, N'Quận Cầu Giấy')
INSERT INTO Quan_Huyen VALUES(2421, 24, N'Quận Đống Đa')
INSERT INTO Quan_Huyen VALUES(2422, 24, N'Quận Hà Đông')
INSERT INTO Quan_Huyen VALUES(2423, 24, N'Quận Hai Bà Trưng')
INSERT INTO Quan_Huyen VALUES(2424, 24, N'Quận Hoàn Kiếm')
INSERT INTO Quan_Huyen VALUES(2425, 24, N'Quận Hoàng Mai')
INSERT INTO Quan_Huyen VALUES(2426, 24, N'Quận Long Biên')
INSERT INTO Quan_Huyen VALUES(2427, 24, N'Quận Nam Từ Liêm')
INSERT INTO Quan_Huyen VALUES(2428, 24, N'Quận Tây Hồ')
INSERT INTO Quan_Huyen VALUES(2429, 24, N'Quận Thanh Xuân')
INSERT INTO Quan_Huyen VALUES(2430, 24, N'Thị xã Sơn Tây')
INSERT INTO Quan_Huyen VALUES(2501, 25, N'Huyện Cẩm Xuyên')
INSERT INTO Quan_Huyen VALUES(2502, 25, N'Huyện Can Lộc')
INSERT INTO Quan_Huyen VALUES(2503, 25, N'Huyện Đức Thọ')
INSERT INTO Quan_Huyen VALUES(2504, 25, N'Huyện Hương Khê')
INSERT INTO Quan_Huyen VALUES(2505, 25, N'Huyện Hương Sơn')
INSERT INTO Quan_Huyen VALUES(2506, 25, N'Huyện Kỳ Anh')
INSERT INTO Quan_Huyen VALUES(2507, 25, N'Huyện Lộc Hà')
INSERT INTO Quan_Huyen VALUES(2508, 25, N'Huyện Nghi Xuân')
INSERT INTO Quan_Huyen VALUES(2509, 25, N'Huyện Thạch Hà')
INSERT INTO Quan_Huyen VALUES(2510, 25, N'Huyện Vũ Quang')
INSERT INTO Quan_Huyen VALUES(2511, 25, N'Thành phố Hà Tĩnh')
INSERT INTO Quan_Huyen VALUES(2512, 25, N'Thị xã Hồng Lĩnh')
INSERT INTO Quan_Huyen VALUES(2513, 25, N'Thị xã Kỳ Anh')
INSERT INTO Quan_Huyen VALUES(2601, 26, N'Huyện Bình Giang')
INSERT INTO Quan_Huyen VALUES(2602, 26, N'Huyện Cẩm Giàng')
INSERT INTO Quan_Huyen VALUES(2603, 26, N'Huyện Gia Lộc')
INSERT INTO Quan_Huyen VALUES(2604, 26, N'Huyện Kim Thành')
INSERT INTO Quan_Huyen VALUES(2605, 26, N'Huyện Nam Sách')
INSERT INTO Quan_Huyen VALUES(2606, 26, N'Huyện Ninh Giang')
INSERT INTO Quan_Huyen VALUES(2607, 26, N'Huyện Thanh Hà')
INSERT INTO Quan_Huyen VALUES(2608, 26, N'Huyện Thanh Miện')
INSERT INTO Quan_Huyen VALUES(2609, 26, N'Huyện Tứ Kỳ')
INSERT INTO Quan_Huyen VALUES(2610, 26, N'Thành phố Chí Linh')
INSERT INTO Quan_Huyen VALUES(2611, 26, N'Thành phố Hải Dương')
INSERT INTO Quan_Huyen VALUES(2612, 26, N'Thị xã Kinh Môn')
INSERT INTO Quan_Huyen VALUES(2701, 27, N'Huyện An Dương')
INSERT INTO Quan_Huyen VALUES(2702, 27, N'Huyện An Lão')
INSERT INTO Quan_Huyen VALUES(2703, 27, N'Huyện Bạch Long Vĩ')
INSERT INTO Quan_Huyen VALUES(2704, 27, N'Huyện Cát Hải')
INSERT INTO Quan_Huyen VALUES(2705, 27, N'Huyện Kiến Thuỵ')
INSERT INTO Quan_Huyen VALUES(2706, 27, N'Huyện Thuỷ Nguyên')
INSERT INTO Quan_Huyen VALUES(2707, 27, N'Huyện Tiên Lãng')
INSERT INTO Quan_Huyen VALUES(2708, 27, N'Huyện Vĩnh Bảo')
INSERT INTO Quan_Huyen VALUES(2709, 27, N'Quận Đồ Sơn')
INSERT INTO Quan_Huyen VALUES(2710, 27, N'Quận Dương Kinh')
INSERT INTO Quan_Huyen VALUES(2711, 27, N'Quận Hải An')
INSERT INTO Quan_Huyen VALUES(2712, 27, N'Quận Hồng Bàng')
INSERT INTO Quan_Huyen VALUES(2713, 27, N'Quận Kiến An')
INSERT INTO Quan_Huyen VALUES(2714, 27, N'Quận Lê Chân')
INSERT INTO Quan_Huyen VALUES(2715, 27, N'Quận Ngô Quyền')
INSERT INTO Quan_Huyen VALUES(2801, 28, N'Huyện Châu Thành')
INSERT INTO Quan_Huyen VALUES(2802, 28, N'Huyện Châu Thành A')
INSERT INTO Quan_Huyen VALUES(2803, 28, N'Huyện Long Mỹ')
INSERT INTO Quan_Huyen VALUES(2804, 28, N'Huyện Phụng Hiệp')
INSERT INTO Quan_Huyen VALUES(2805, 28, N'Huyện Vị Thuỷ')
INSERT INTO Quan_Huyen VALUES(2806, 28, N'Thành phố Ngã Bảy')
INSERT INTO Quan_Huyen VALUES(2807, 28, N'Thành phố Vị Thanh')
INSERT INTO Quan_Huyen VALUES(2808, 28, N'Thị xã Long Mỹ')
INSERT INTO Quan_Huyen VALUES(2901, 29, N'Huyện Cao Phong')
INSERT INTO Quan_Huyen VALUES(2902, 29, N'Huyện Đà Bắc')
INSERT INTO Quan_Huyen VALUES(2903, 29, N'Huyện Kim Bôi')
INSERT INTO Quan_Huyen VALUES(2904, 29, N'Huyện Lạc Sơn')
INSERT INTO Quan_Huyen VALUES(2905, 29, N'Huyện Lạc Thủy')
INSERT INTO Quan_Huyen VALUES(2906, 29, N'Huyện Lương Sơn')
INSERT INTO Quan_Huyen VALUES(2907, 29, N'Huyện Mai Châu')
INSERT INTO Quan_Huyen VALUES(2908, 29, N'Huyện Tân Lạc')
INSERT INTO Quan_Huyen VALUES(2909, 29, N'Huyện Yên Thủy')
INSERT INTO Quan_Huyen VALUES(2910, 29, N'Thành phố Hòa Bình')
INSERT INTO Quan_Huyen VALUES(3001, 30, N'Huyện Ân Thi')
INSERT INTO Quan_Huyen VALUES(3002, 30, N'Huyện Khoái Châu')
INSERT INTO Quan_Huyen VALUES(3003, 30, N'Huyện Kim Động')
INSERT INTO Quan_Huyen VALUES(3004, 30, N'Huyện Phù Cừ')
INSERT INTO Quan_Huyen VALUES(3005, 30, N'Huyện Tiên Lữ')
INSERT INTO Quan_Huyen VALUES(3006, 30, N'Huyện Văn Giang')
INSERT INTO Quan_Huyen VALUES(3007, 30, N'Huyện Văn Lâm')
INSERT INTO Quan_Huyen VALUES(3008, 30, N'Huyện Yên Mỹ')
INSERT INTO Quan_Huyen VALUES(3009, 30, N'Thành phố Hưng Yên')
INSERT INTO Quan_Huyen VALUES(3010, 30, N'Thị xã Mỹ Hào')
INSERT INTO Quan_Huyen VALUES(3101, 31, N'Huyện Cam Lâm')
INSERT INTO Quan_Huyen VALUES(3102, 31, N'Huyện Diên Khánh')
INSERT INTO Quan_Huyen VALUES(3103, 31, N'Huyện Khánh Sơn')
INSERT INTO Quan_Huyen VALUES(3104, 31, N'Huyện Khánh Vĩnh')
INSERT INTO Quan_Huyen VALUES(3105, 31, N'Huyện Trường Sa')
INSERT INTO Quan_Huyen VALUES(3106, 31, N'Huyện Vạn Ninh')
INSERT INTO Quan_Huyen VALUES(3107, 31, N'Thành phố Cam Ranh')
INSERT INTO Quan_Huyen VALUES(3108, 31, N'Thành phố Nha Trang')
INSERT INTO Quan_Huyen VALUES(3109, 31, N'Thị xã Ninh Hòa')
INSERT INTO Quan_Huyen VALUES(3201, 32, N'Huyện An Biên')
INSERT INTO Quan_Huyen VALUES(3202, 32, N'Huyện An Minh')
INSERT INTO Quan_Huyen VALUES(3203, 32, N'Huyện Châu Thành')
INSERT INTO Quan_Huyen VALUES(3204, 32, N'Huyện Giang Thành')
INSERT INTO Quan_Huyen VALUES(3205, 32, N'Huyện Giồng Riềng')
INSERT INTO Quan_Huyen VALUES(3206, 32, N'Huyện Gò Quao')
INSERT INTO Quan_Huyen VALUES(3207, 32, N'Huyện Hòn Đất')
INSERT INTO Quan_Huyen VALUES(3208, 32, N'Huyện Kiên Hải')
INSERT INTO Quan_Huyen VALUES(3209, 32, N'Huyện Kiên Lương')
INSERT INTO Quan_Huyen VALUES(3210, 32, N'Huyện Tân Hiệp')
INSERT INTO Quan_Huyen VALUES(3211, 32, N'Huyện U Minh Thượng')
INSERT INTO Quan_Huyen VALUES(3212, 32, N'Huyện Vĩnh Thuận')
INSERT INTO Quan_Huyen VALUES(3213, 32, N'Thành phố Hà Tiên')
INSERT INTO Quan_Huyen VALUES(3214, 32, N'Thành phố Phú Quốc')
INSERT INTO Quan_Huyen VALUES(3215, 32, N'Thành phố Rạch Giá')
INSERT INTO Quan_Huyen VALUES(3301, 33, N'Huyện Đắk Glei')
INSERT INTO Quan_Huyen VALUES(3302, 33, N'Huyện Đắk Hà')
INSERT INTO Quan_Huyen VALUES(3303, 33, N'Huyện Đắk Tô')
INSERT INTO Quan_Huyen VALUES(3304, 33, N'Huyện Ia H. Drai')
INSERT INTO Quan_Huyen VALUES(3305, 33, N'Huyện Kon Plông')
INSERT INTO Quan_Huyen VALUES(3306, 33, N'Huyện Kon Rẫy')
INSERT INTO Quan_Huyen VALUES(3307, 33, N'Huyện Ngọc Hồi')
INSERT INTO Quan_Huyen VALUES(3308, 33, N'Huyện Sa Thầy')
INSERT INTO Quan_Huyen VALUES(3309, 33, N'Huyện Tu Mơ Rông')
INSERT INTO Quan_Huyen VALUES(3310, 33, N'Thành phố Kon Tum')
INSERT INTO Quan_Huyen VALUES(3401, 34, N'Huyện Mường Tè')
INSERT INTO Quan_Huyen VALUES(3402, 34, N'Huyện Nậm Nhùn')
INSERT INTO Quan_Huyen VALUES(3403, 34, N'Huyện Phong Thổ')
INSERT INTO Quan_Huyen VALUES(3404, 34, N'Huyện Sìn Hồ')
INSERT INTO Quan_Huyen VALUES(3405, 34, N'Huyện Tam Đường')
INSERT INTO Quan_Huyen VALUES(3406, 34, N'Huyện Tân Uyên')
INSERT INTO Quan_Huyen VALUES(3407, 34, N'Huyện Than Uyên')
INSERT INTO Quan_Huyen VALUES(3408, 34, N'Thành phố Lai Châu')
INSERT INTO Quan_Huyen VALUES(3501, 35, N'Huyện Bảo Lâm')
INSERT INTO Quan_Huyen VALUES(3502, 35, N'Huyện Cát Tiên')
INSERT INTO Quan_Huyen VALUES(3503, 35, N'Huyện Đạ Huoai')
INSERT INTO Quan_Huyen VALUES(3504, 35, N'Huyện Đạ Tẻh')
INSERT INTO Quan_Huyen VALUES(3505, 35, N'Huyện Đam Rông')
INSERT INTO Quan_Huyen VALUES(3506, 35, N'Huyện Di Linh')
INSERT INTO Quan_Huyen VALUES(3507, 35, N'Huyện Đơn Dương')
INSERT INTO Quan_Huyen VALUES(3508, 35, N'Huyện Đức Trọng')
INSERT INTO Quan_Huyen VALUES(3509, 35, N'Huyện Lạc Dương')
INSERT INTO Quan_Huyen VALUES(3510, 35, N'Huyện Lâm Hà')
INSERT INTO Quan_Huyen VALUES(3511, 35, N'Thành phố Bảo Lộc')
INSERT INTO Quan_Huyen VALUES(3512, 35, N'Thành phố Đà Lạt')
INSERT INTO Quan_Huyen VALUES(3601, 36, N'Huyện Bắc Sơn')
INSERT INTO Quan_Huyen VALUES(3602, 36, N'Huyện Bình Gia')
INSERT INTO Quan_Huyen VALUES(3603, 36, N'Huyện Cao Lộc')
INSERT INTO Quan_Huyen VALUES(3604, 36, N'Huyện Chi Lăng')
INSERT INTO Quan_Huyen VALUES(3605, 36, N'Huyện Đình Lập')
INSERT INTO Quan_Huyen VALUES(3606, 36, N'Huyện Hữu Lũng')
INSERT INTO Quan_Huyen VALUES(3607, 36, N'Huyện Lộc Bình')
INSERT INTO Quan_Huyen VALUES(3608, 36, N'Huyện Tràng Định')
INSERT INTO Quan_Huyen VALUES(3609, 36, N'Huyện Văn Lãng')
INSERT INTO Quan_Huyen VALUES(3610, 36, N'Huyện Văn Quan')
INSERT INTO Quan_Huyen VALUES(3611, 36, N'Thành phố Lạng Sơn')
INSERT INTO Quan_Huyen VALUES(3701, 37, N'Huyện Bắc Hà')
INSERT INTO Quan_Huyen VALUES(3702, 37, N'Huyện Bảo Thắng')
INSERT INTO Quan_Huyen VALUES(3703, 37, N'Huyện Bảo Yên')
INSERT INTO Quan_Huyen VALUES(3704, 37, N'Huyện Bát Xát')
INSERT INTO Quan_Huyen VALUES(3705, 37, N'Huyện Mường Khương')
INSERT INTO Quan_Huyen VALUES(3706, 37, N'Huyện Si Ma Cai')
INSERT INTO Quan_Huyen VALUES(3707, 37, N'Huyện Văn Bàn')
INSERT INTO Quan_Huyen VALUES(3708, 37, N'Thành phố Lào Cai')
INSERT INTO Quan_Huyen VALUES(3709, 37, N'Thị xã Sa Pa')
INSERT INTO Quan_Huyen VALUES(3801, 38, N'Huyện Bến Lức')
INSERT INTO Quan_Huyen VALUES(3802, 38, N'Huyện Cần Đước')
INSERT INTO Quan_Huyen VALUES(3803, 38, N'Huyện Cần Giuộc')
INSERT INTO Quan_Huyen VALUES(3804, 38, N'Huyện Châu Thành')
INSERT INTO Quan_Huyen VALUES(3805, 38, N'Huyện Đức Hòa')
INSERT INTO Quan_Huyen VALUES(3806, 38, N'Huyện Đức Huệ')
INSERT INTO Quan_Huyen VALUES(3807, 38, N'Huyện Mộc Hóa')
INSERT INTO Quan_Huyen VALUES(3808, 38, N'Huyện Tân Hưng')
INSERT INTO Quan_Huyen VALUES(3809, 38, N'Huyện Tân Thạnh')
INSERT INTO Quan_Huyen VALUES(3810, 38, N'Huyện Tân Trụ')
INSERT INTO Quan_Huyen VALUES(3811, 38, N'Huyện Thạnh Hóa')
INSERT INTO Quan_Huyen VALUES(3812, 38, N'Huyện Thủ Thừa')
INSERT INTO Quan_Huyen VALUES(3813, 38, N'Huyện Vĩnh Hưng')
INSERT INTO Quan_Huyen VALUES(3814, 38, N'Thành phố Tân An')
INSERT INTO Quan_Huyen VALUES(3815, 38, N'Thị xã Kiến Tường')
INSERT INTO Quan_Huyen VALUES(3901, 39, N'Huyện Giao Thủy')
INSERT INTO Quan_Huyen VALUES(3902, 39, N'Huyện Hải Hậu')
INSERT INTO Quan_Huyen VALUES(3903, 39, N'Huyện Mỹ Lộc')
INSERT INTO Quan_Huyen VALUES(3904, 39, N'Huyện Nam Trực')
INSERT INTO Quan_Huyen VALUES(3905, 39, N'Huyện Nghĩa Hưng')
INSERT INTO Quan_Huyen VALUES(3906, 39, N'Huyện Trực Ninh')
INSERT INTO Quan_Huyen VALUES(3907, 39, N'Huyện Vụ Bản')
INSERT INTO Quan_Huyen VALUES(3908, 39, N'Huyện Xuân Trường')
INSERT INTO Quan_Huyen VALUES(3909, 39, N'Huyện Ý Yên')
INSERT INTO Quan_Huyen VALUES(3910, 39, N'Thành phố Nam Định')
INSERT INTO Quan_Huyen VALUES(4001, 40, N'Huyện Anh Sơn')
INSERT INTO Quan_Huyen VALUES(4002, 40, N'Huyện Con Cuông')
INSERT INTO Quan_Huyen VALUES(4003, 40, N'Huyện Diễn Châu')
INSERT INTO Quan_Huyen VALUES(4004, 40, N'Huyện Đô Lương')
INSERT INTO Quan_Huyen VALUES(4005, 40, N'Huyện Hưng Nguyên')
INSERT INTO Quan_Huyen VALUES(4006, 40, N'Huyện Kỳ Sơn')
INSERT INTO Quan_Huyen VALUES(4007, 40, N'Huyện Nam Đàn')
INSERT INTO Quan_Huyen VALUES(4008, 40, N'Huyện Nghi Lộc')
INSERT INTO Quan_Huyen VALUES(4009, 40, N'Huyện Nghĩa Đàn')
INSERT INTO Quan_Huyen VALUES(4010, 40, N'Huyện Quế Phong')
INSERT INTO Quan_Huyen VALUES(4011, 40, N'Huyện Quỳ Châu')
INSERT INTO Quan_Huyen VALUES(4012, 40, N'Huyện Quỳ Hợp')
INSERT INTO Quan_Huyen VALUES(4013, 40, N'Huyện Quỳnh Lưu')
INSERT INTO Quan_Huyen VALUES(4014, 40, N'Huyện Tân Kỳ')
INSERT INTO Quan_Huyen VALUES(4015, 40, N'Huyện Thanh Chương')
INSERT INTO Quan_Huyen VALUES(4016, 40, N'Huyện Tương Dương')
INSERT INTO Quan_Huyen VALUES(4017, 40, N'Huyện Yên Thành')
INSERT INTO Quan_Huyen VALUES(4018, 40, N'Thành phố Vinh')
INSERT INTO Quan_Huyen VALUES(4019, 40, N'Thị xã Cửa Lò')
INSERT INTO Quan_Huyen VALUES(4020, 40, N'Thị xã Hoàng Mai')
INSERT INTO Quan_Huyen VALUES(4021, 40, N'Thị xã Thái Hoà')
INSERT INTO Quan_Huyen VALUES(4101, 41, N'Huyện Gia Viễn')
INSERT INTO Quan_Huyen VALUES(4102, 41, N'Huyện Hoa Lư')
INSERT INTO Quan_Huyen VALUES(4103, 41, N'Huyện Kim Sơn')
INSERT INTO Quan_Huyen VALUES(4104, 41, N'Huyện Nho Quan')
INSERT INTO Quan_Huyen VALUES(4105, 41, N'Huyện Yên Khánh')
INSERT INTO Quan_Huyen VALUES(4106, 41, N'Huyện Yên Mô')
INSERT INTO Quan_Huyen VALUES(4107, 41, N'Thành phố Ninh Bình')
INSERT INTO Quan_Huyen VALUES(4108, 41, N'Thành phố Tam Điệp')
INSERT INTO Quan_Huyen VALUES(4201, 42, N'Huyện Bác Ái')
INSERT INTO Quan_Huyen VALUES(4202, 42, N'Huyện Ninh Hải')
INSERT INTO Quan_Huyen VALUES(4203, 42, N'Huyện Ninh Phước')
INSERT INTO Quan_Huyen VALUES(4204, 42, N'Huyện Ninh Sơn')
INSERT INTO Quan_Huyen VALUES(4205, 42, N'Huyện Thuận Bắc')
INSERT INTO Quan_Huyen VALUES(4206, 42, N'Huyện Thuận Nam')
INSERT INTO Quan_Huyen VALUES(4207, 42, N'Thành phố Phan Rang-Tháp Chàm')
INSERT INTO Quan_Huyen VALUES(4301, 43, N'Huyện Cẩm Khê')
INSERT INTO Quan_Huyen VALUES(4302, 43, N'Huyện Đoan Hùng')
INSERT INTO Quan_Huyen VALUES(4303, 43, N'Huyện Hạ Hoà')
INSERT INTO Quan_Huyen VALUES(4304, 43, N'Huyện Lâm Thao')
INSERT INTO Quan_Huyen VALUES(4305, 43, N'Huyện Phù Ninh')
INSERT INTO Quan_Huyen VALUES(4306, 43, N'Huyện Tam Nông')
INSERT INTO Quan_Huyen VALUES(4307, 43, N'Huyện Tân Sơn')
INSERT INTO Quan_Huyen VALUES(4308, 43, N'Huyện Thanh Ba')
INSERT INTO Quan_Huyen VALUES(4309, 43, N'Huyện Thanh Sơn')
INSERT INTO Quan_Huyen VALUES(4310, 43, N'Huyện Thanh Thuỷ')
INSERT INTO Quan_Huyen VALUES(4311, 43, N'Huyện Yên Lập')
INSERT INTO Quan_Huyen VALUES(4312, 43, N'Thành phố Việt Trì')
INSERT INTO Quan_Huyen VALUES(4313, 43, N'Thị xã Phú Thọ')
INSERT INTO Quan_Huyen VALUES(4401, 44, N'Huyện Đồng Xuân')
INSERT INTO Quan_Huyen VALUES(4402, 44, N'Huyện Phú Hoà')
INSERT INTO Quan_Huyen VALUES(4403, 44, N'Huyện Sơn Hòa')
INSERT INTO Quan_Huyen VALUES(4404, 44, N'Huyện Sông Hinh')
INSERT INTO Quan_Huyen VALUES(4405, 44, N'Huyện Tây Hoà')
INSERT INTO Quan_Huyen VALUES(4406, 44, N'Huyện Tuy An')
INSERT INTO Quan_Huyen VALUES(4407, 44, N'Thành phố Tuy Hoà')
INSERT INTO Quan_Huyen VALUES(4408, 44, N'Thị xã Đông Hòa')
INSERT INTO Quan_Huyen VALUES(4409, 44, N'Thị xã Sông Cầu')
INSERT INTO Quan_Huyen VALUES(4501, 45, N'Huyện Bố Trạch')
INSERT INTO Quan_Huyen VALUES(4502, 45, N'Huyện Lệ Thủy')
INSERT INTO Quan_Huyen VALUES(4503, 45, N'Huyện Minh Hóa')
INSERT INTO Quan_Huyen VALUES(4504, 45, N'Huyện Quảng Ninh')
INSERT INTO Quan_Huyen VALUES(4505, 45, N'Huyện Quảng Trạch')
INSERT INTO Quan_Huyen VALUES(4506, 45, N'Huyện Tuyên Hóa')
INSERT INTO Quan_Huyen VALUES(4507, 45, N'Thành Phố Đồng Hới')
INSERT INTO Quan_Huyen VALUES(4508, 45, N'Thị xã Ba Đồn')
INSERT INTO Quan_Huyen VALUES(4601, 46, N'Huyện Bắc Trà My')
INSERT INTO Quan_Huyen VALUES(4602, 46, N'Huyện Đại Lộc')
INSERT INTO Quan_Huyen VALUES(4603, 46, N'Huyện Đông Giang')
INSERT INTO Quan_Huyen VALUES(4604, 46, N'Huyện Duy Xuyên')
INSERT INTO Quan_Huyen VALUES(4605, 46, N'Huyện Hiệp Đức')
INSERT INTO Quan_Huyen VALUES(4606, 46, N'Huyện Nam Giang')
INSERT INTO Quan_Huyen VALUES(4607, 46, N'Huyện Nam Trà My')
INSERT INTO Quan_Huyen VALUES(4608, 46, N'Huyện Nông Sơn')
INSERT INTO Quan_Huyen VALUES(4609, 46, N'Huyện Núi Thành')
INSERT INTO Quan_Huyen VALUES(4610, 46, N'Huyện Phú Ninh')
INSERT INTO Quan_Huyen VALUES(4611, 46, N'Huyện Phước Sơn')
INSERT INTO Quan_Huyen VALUES(4612, 46, N'Huyện Quế Sơn')
INSERT INTO Quan_Huyen VALUES(4613, 46, N'Huyện Tây Giang')
INSERT INTO Quan_Huyen VALUES(4614, 46, N'Huyện Thăng Bình')
INSERT INTO Quan_Huyen VALUES(4615, 46, N'Huyện Tiên Phước')
INSERT INTO Quan_Huyen VALUES(4616, 46, N'Thành phố Hội An')
INSERT INTO Quan_Huyen VALUES(4617, 46, N'Thành phố Tam Kỳ')
INSERT INTO Quan_Huyen VALUES(4618, 46, N'Thị xã Điện Bàn')
INSERT INTO Quan_Huyen VALUES(4701, 47, N'Huyện Ba Tơ')
INSERT INTO Quan_Huyen VALUES(4702, 47, N'Huyện Bình Sơn')
INSERT INTO Quan_Huyen VALUES(4703, 47, N'Huyện Lý Sơn')
INSERT INTO Quan_Huyen VALUES(4704, 47, N'Huyện Minh Long')
INSERT INTO Quan_Huyen VALUES(4705, 47, N'Huyện Mộ Đức')
INSERT INTO Quan_Huyen VALUES(4706, 47, N'Huyện Nghĩa Hành')
INSERT INTO Quan_Huyen VALUES(4707, 47, N'Huyện Sơn Hà')
INSERT INTO Quan_Huyen VALUES(4708, 47, N'Huyện Sơn Tây')
INSERT INTO Quan_Huyen VALUES(4709, 47, N'Huyện Sơn Tịnh')
INSERT INTO Quan_Huyen VALUES(4710, 47, N'Huyện Trà Bồng')
INSERT INTO Quan_Huyen VALUES(4711, 47, N'Huyện Tư Nghĩa')
INSERT INTO Quan_Huyen VALUES(4712, 47, N'Thành phố Quảng Ngãi')
INSERT INTO Quan_Huyen VALUES(4713, 47, N'Thị xã Đức Phổ')
INSERT INTO Quan_Huyen VALUES(4801, 48, N'Huyện Ba Chẽ')
INSERT INTO Quan_Huyen VALUES(4802, 48, N'Huyện Bình Liêu')
INSERT INTO Quan_Huyen VALUES(4803, 48, N'Huyện Cô Tô')
INSERT INTO Quan_Huyen VALUES(4804, 48, N'Huyện Đầm Hà')
INSERT INTO Quan_Huyen VALUES(4805, 48, N'Huyện Hải Hà')
INSERT INTO Quan_Huyen VALUES(4806, 48, N'Huyện Tiên Yên')
INSERT INTO Quan_Huyen VALUES(4807, 48, N'Huyện Vân Đồn')
INSERT INTO Quan_Huyen VALUES(4808, 48, N'Thành phố Cẩm Phả')
INSERT INTO Quan_Huyen VALUES(4809, 48, N'Thành phố Hạ Long')
INSERT INTO Quan_Huyen VALUES(4810, 48, N'Thành phố Móng Cái')
INSERT INTO Quan_Huyen VALUES(4811, 48, N'Thành phố Uông Bí')
INSERT INTO Quan_Huyen VALUES(4812, 48, N'Thị xã Đông Triều')
INSERT INTO Quan_Huyen VALUES(4813, 48, N'Thị xã Quảng Yên')
INSERT INTO Quan_Huyen VALUES(4901, 49, N'Huyện Cam Lộ')
INSERT INTO Quan_Huyen VALUES(4902, 49, N'Huyện Cồn Cỏ')
INSERT INTO Quan_Huyen VALUES(4903, 49, N'Huyện Đa Krông')
INSERT INTO Quan_Huyen VALUES(4904, 49, N'Huyện Gio Linh')
INSERT INTO Quan_Huyen VALUES(4905, 49, N'Huyện Hải Lăng')
INSERT INTO Quan_Huyen VALUES(4906, 49, N'Huyện Hướng Hóa')
INSERT INTO Quan_Huyen VALUES(4907, 49, N'Huyện Triệu Phong')
INSERT INTO Quan_Huyen VALUES(4908, 49, N'Huyện Vĩnh Linh')
INSERT INTO Quan_Huyen VALUES(4909, 49, N'Thành phố Đông Hà')
INSERT INTO Quan_Huyen VALUES(4910, 49, N'Thị xã Quảng Trị')
INSERT INTO Quan_Huyen VALUES(5001, 50, N'Huyện Châu Thành')
INSERT INTO Quan_Huyen VALUES(5002, 50, N'Huyện Cù Lao Dung')
INSERT INTO Quan_Huyen VALUES(5003, 50, N'Huyện Kế Sách')
INSERT INTO Quan_Huyen VALUES(5004, 50, N'Huyện Long Phú')
INSERT INTO Quan_Huyen VALUES(5005, 50, N'Huyện Mỹ Tú')
INSERT INTO Quan_Huyen VALUES(5006, 50, N'Huyện Mỹ Xuyên')
INSERT INTO Quan_Huyen VALUES(5007, 50, N'Huyện Thạnh Trị')
INSERT INTO Quan_Huyen VALUES(5008, 50, N'Huyện Trần Đề')
INSERT INTO Quan_Huyen VALUES(5009, 50, N'Thành phố Sóc Trăng')
INSERT INTO Quan_Huyen VALUES(5010, 50, N'Thị xã Ngã Năm')
INSERT INTO Quan_Huyen VALUES(5011, 50, N'Thị xã Vĩnh Châu')
INSERT INTO Quan_Huyen VALUES(5101, 51, N'Huyện Bắc Yên')
INSERT INTO Quan_Huyen VALUES(5102, 51, N'Huyện Mai Sơn')
INSERT INTO Quan_Huyen VALUES(5103, 51, N'Huyện Mộc Châu')
INSERT INTO Quan_Huyen VALUES(5104, 51, N'Huyện Mường La')
INSERT INTO Quan_Huyen VALUES(5105, 51, N'Huyện Phù Yên')
INSERT INTO Quan_Huyen VALUES(5106, 51, N'Huyện Quỳnh Nhai')
INSERT INTO Quan_Huyen VALUES(5107, 51, N'Huyện Sông Mã')
INSERT INTO Quan_Huyen VALUES(5108, 51, N'Huyện Sốp Cộp')
INSERT INTO Quan_Huyen VALUES(5109, 51, N'Huyện Thuận Châu')
INSERT INTO Quan_Huyen VALUES(5110, 51, N'Huyện Vân Hồ')
INSERT INTO Quan_Huyen VALUES(5111, 51, N'Huyện Yên Châu')
INSERT INTO Quan_Huyen VALUES(5112, 51, N'Thành phố Sơn La')
INSERT INTO Quan_Huyen VALUES(5201, 52, N'Huyện Bến Cầu')
INSERT INTO Quan_Huyen VALUES(5202, 52, N'Huyện Châu Thành')
INSERT INTO Quan_Huyen VALUES(5203, 52, N'Huyện Dương Minh Châu')
INSERT INTO Quan_Huyen VALUES(5204, 52, N'Huyện Gò Dầu')
INSERT INTO Quan_Huyen VALUES(5205, 52, N'Huyện Tân Biên')
INSERT INTO Quan_Huyen VALUES(5206, 52, N'Huyện Tân Châu')
INSERT INTO Quan_Huyen VALUES(5207, 52, N'Thành phố Tây Ninh')
INSERT INTO Quan_Huyen VALUES(5208, 52, N'Thị xã Hòa Thành')
INSERT INTO Quan_Huyen VALUES(5209, 52, N'Thị xã Trảng Bàng')
INSERT INTO Quan_Huyen VALUES(5301, 53, N'Huyện Đông Hưng')
INSERT INTO Quan_Huyen VALUES(5302, 53, N'Huyện Hưng Hà')
INSERT INTO Quan_Huyen VALUES(5303, 53, N'Huyện Kiến Xương')
INSERT INTO Quan_Huyen VALUES(5304, 53, N'Huyện Quỳnh Phụ')
INSERT INTO Quan_Huyen VALUES(5305, 53, N'Huyện Thái Thụy')
INSERT INTO Quan_Huyen VALUES(5306, 53, N'Huyện Tiền Hải')
INSERT INTO Quan_Huyen VALUES(5307, 53, N'Huyện Vũ Thư')
INSERT INTO Quan_Huyen VALUES(5308, 53, N'Thành phố Thái Bình')
INSERT INTO Quan_Huyen VALUES(5401, 54, N'Huyện Đại Từ')
INSERT INTO Quan_Huyen VALUES(5402, 54, N'Huyện Định Hóa')
INSERT INTO Quan_Huyen VALUES(5403, 54, N'Huyện Đồng Hỷ')
INSERT INTO Quan_Huyen VALUES(5404, 54, N'Huyện Phú Bình')
INSERT INTO Quan_Huyen VALUES(5405, 54, N'Huyện Phú Lương')
INSERT INTO Quan_Huyen VALUES(5406, 54, N'Huyện Võ Nhai')
INSERT INTO Quan_Huyen VALUES(5407, 54, N'Thành phố Phổ Yên')
INSERT INTO Quan_Huyen VALUES(5408, 54, N'Thành phố Sông Công')
INSERT INTO Quan_Huyen VALUES(5409, 54, N'Thành phố Thái Nguyên')
INSERT INTO Quan_Huyen VALUES(5501, 55, N'Huyện Bá Thước')
INSERT INTO Quan_Huyen VALUES(5502, 55, N'Huyện Cẩm Thủy')
INSERT INTO Quan_Huyen VALUES(5503, 55, N'Huyện Đông Sơn')
INSERT INTO Quan_Huyen VALUES(5504, 55, N'Huyện Hà Trung')
INSERT INTO Quan_Huyen VALUES(5505, 55, N'Huyện Hậu Lộc')
INSERT INTO Quan_Huyen VALUES(5506, 55, N'Huyện Hoằng Hóa')
INSERT INTO Quan_Huyen VALUES(5507, 55, N'Huyện Lang Chánh')
INSERT INTO Quan_Huyen VALUES(5508, 55, N'Huyện Mường Lát')
INSERT INTO Quan_Huyen VALUES(5509, 55, N'Huyện Nga Sơn')
INSERT INTO Quan_Huyen VALUES(5510, 55, N'Huyện Ngọc Lặc')
INSERT INTO Quan_Huyen VALUES(5511, 55, N'Huyện Như Thanh')
INSERT INTO Quan_Huyen VALUES(5512, 55, N'Huyện Như Xuân')
INSERT INTO Quan_Huyen VALUES(5513, 55, N'Huyện Nông Cống')
INSERT INTO Quan_Huyen VALUES(5514, 55, N'Huyện Quan Hóa')
INSERT INTO Quan_Huyen VALUES(5515, 55, N'Huyện Quan Sơn')
INSERT INTO Quan_Huyen VALUES(5516, 55, N'Huyện Quảng Xương')
INSERT INTO Quan_Huyen VALUES(5517, 55, N'Huyện Thạch Thành')
INSERT INTO Quan_Huyen VALUES(5518, 55, N'Huyện Thiệu Hóa')
INSERT INTO Quan_Huyen VALUES(5519, 55, N'Huyện Thọ Xuân')
INSERT INTO Quan_Huyen VALUES(5520, 55, N'Huyện Thường Xuân')
INSERT INTO Quan_Huyen VALUES(5521, 55, N'Huyện Triệu Sơn')
INSERT INTO Quan_Huyen VALUES(5522, 55, N'Huyện Vĩnh Lộc')
INSERT INTO Quan_Huyen VALUES(5523, 55, N'Huyện Yên Định')
INSERT INTO Quan_Huyen VALUES(5524, 55, N'Thành phố Sầm Sơn')
INSERT INTO Quan_Huyen VALUES(5525, 55, N'Thành phố Thanh Hóa')
INSERT INTO Quan_Huyen VALUES(5526, 55, N'Thị xã Bỉm Sơn')
INSERT INTO Quan_Huyen VALUES(5527, 55, N'Thị xã Nghi Sơn')
INSERT INTO Quan_Huyen VALUES(5601, 56, N'Huyện Cái Bè')
INSERT INTO Quan_Huyen VALUES(5602, 56, N'Huyện Cai Lậy')
INSERT INTO Quan_Huyen VALUES(5603, 56, N'Huyện Châu Thành')
INSERT INTO Quan_Huyen VALUES(5604, 56, N'Huyện Chợ Gạo')
INSERT INTO Quan_Huyen VALUES(5605, 56, N'Huyện Gò Công Đông')
INSERT INTO Quan_Huyen VALUES(5606, 56, N'Huyện Gò Công Tây')
INSERT INTO Quan_Huyen VALUES(5607, 56, N'Huyện Tân Phú Đông')
INSERT INTO Quan_Huyen VALUES(5608, 56, N'Huyện Tân Phước')
INSERT INTO Quan_Huyen VALUES(5609, 56, N'Thành phố Mỹ Tho')
INSERT INTO Quan_Huyen VALUES(5610, 56, N'Thị xã Cai Lậy')
INSERT INTO Quan_Huyen VALUES(5611, 56, N'Thị xã Gò Công')
INSERT INTO Quan_Huyen VALUES(5701, 57, N'Huyện Bình Chánh')
INSERT INTO Quan_Huyen VALUES(5702, 57, N'Huyện Cần Giờ')
INSERT INTO Quan_Huyen VALUES(5703, 57, N'Huyện Củ Chi')
INSERT INTO Quan_Huyen VALUES(5704, 57, N'Huyện Hóc Môn')
INSERT INTO Quan_Huyen VALUES(5705, 57, N'Huyện Nhà Bè')
INSERT INTO Quan_Huyen VALUES(5706, 57, N'Quận 1')
INSERT INTO Quan_Huyen VALUES(5707, 57, N'Quận 10')
INSERT INTO Quan_Huyen VALUES(5708, 57, N'Quận 11')
INSERT INTO Quan_Huyen VALUES(5709, 57, N'Quận 12')
INSERT INTO Quan_Huyen VALUES(5710, 57, N'Quận 3')
INSERT INTO Quan_Huyen VALUES(5711, 57, N'Quận 4')
INSERT INTO Quan_Huyen VALUES(5712, 57, N'Quận 5')
INSERT INTO Quan_Huyen VALUES(5713, 57, N'Quận 6')
INSERT INTO Quan_Huyen VALUES(5714, 57, N'Quận 7')
INSERT INTO Quan_Huyen VALUES(5715, 57, N'Quận 8')
INSERT INTO Quan_Huyen VALUES(5716, 57, N'Quận Bình Tân')
INSERT INTO Quan_Huyen VALUES(5717, 57, N'Quận Bình Thạnh')
INSERT INTO Quan_Huyen VALUES(5718, 57, N'Quận Gò Vấp')
INSERT INTO Quan_Huyen VALUES(5719, 57, N'Quận Phú Nhuận')
INSERT INTO Quan_Huyen VALUES(5720, 57, N'Quận Tân Bình')
INSERT INTO Quan_Huyen VALUES(5721, 57, N'Quận Tân Phú')
INSERT INTO Quan_Huyen VALUES(5722, 57, N'Thành phố Thủ Đức')
INSERT INTO Quan_Huyen VALUES(5801, 58, N'Huyện Càng Long')
INSERT INTO Quan_Huyen VALUES(5802, 58, N'Huyện Cầu Kè')
INSERT INTO Quan_Huyen VALUES(5803, 58, N'Huyện Cầu Ngang')
INSERT INTO Quan_Huyen VALUES(5804, 58, N'Huyện Châu Thành')
INSERT INTO Quan_Huyen VALUES(5805, 58, N'Huyện Duyên Hải')
INSERT INTO Quan_Huyen VALUES(5806, 58, N'Huyện Tiểu Cần')
INSERT INTO Quan_Huyen VALUES(5807, 58, N'Huyện Trà Cú')
INSERT INTO Quan_Huyen VALUES(5808, 58, N'Thành phố Trà Vinh')
INSERT INTO Quan_Huyen VALUES(5809, 58, N'Thị xã Duyên Hải')
INSERT INTO Quan_Huyen VALUES(5901, 59, N'Huyện A Lưới')
INSERT INTO Quan_Huyen VALUES(5902, 59, N'Huyện Nam Đông')
INSERT INTO Quan_Huyen VALUES(5903, 59, N'Huyện Phong Điền')
INSERT INTO Quan_Huyen VALUES(5904, 59, N'Huyện Phú Lộc')
INSERT INTO Quan_Huyen VALUES(5905, 59, N'Huyện Phú Vang')
INSERT INTO Quan_Huyen VALUES(5906, 59, N'Huyện Quảng Điền')
INSERT INTO Quan_Huyen VALUES(5907, 59, N'Thành phố Huế')
INSERT INTO Quan_Huyen VALUES(5908, 59, N'Thị xã Hương Thủy')
INSERT INTO Quan_Huyen VALUES(5909, 59, N'Thị xã Hương Trà')
INSERT INTO Quan_Huyen VALUES(6001, 60, N'Huyện Chiêm Hóa')
INSERT INTO Quan_Huyen VALUES(6002, 60, N'Huyện Hàm Yên')
INSERT INTO Quan_Huyen VALUES(6003, 60, N'Huyện Lâm Bình')
INSERT INTO Quan_Huyen VALUES(6004, 60, N'Huyện Na Hang')
INSERT INTO Quan_Huyen VALUES(6005, 60, N'Huyện Sơn Dương')
INSERT INTO Quan_Huyen VALUES(6006, 60, N'Huyện Yên Sơn')
INSERT INTO Quan_Huyen VALUES(6007, 60, N'Thành phố Tuyên Quang')
INSERT INTO Quan_Huyen VALUES(6101, 61, N'Huyện  Vũng Liêm')
INSERT INTO Quan_Huyen VALUES(6102, 61, N'Huyện Bình Tân')
INSERT INTO Quan_Huyen VALUES(6103, 61, N'Huyện Long Hồ')
INSERT INTO Quan_Huyen VALUES(6104, 61, N'Huyện Mang Thít')
INSERT INTO Quan_Huyen VALUES(6105, 61, N'Huyện Tam Bình')
INSERT INTO Quan_Huyen VALUES(6106, 61, N'Huyện Trà Ôn')
INSERT INTO Quan_Huyen VALUES(6107, 61, N'Thành phố Vĩnh Long')
INSERT INTO Quan_Huyen VALUES(6108, 61, N'Thị xã Bình Minh')
INSERT INTO Quan_Huyen VALUES(6201, 62, N'Huyện Bình Xuyên')
INSERT INTO Quan_Huyen VALUES(6202, 62, N'Huyện Lập Thạch')
INSERT INTO Quan_Huyen VALUES(6203, 62, N'Huyện Sông Lô')
INSERT INTO Quan_Huyen VALUES(6204, 62, N'Huyện Tam Đảo')
INSERT INTO Quan_Huyen VALUES(6205, 62, N'Huyện Tam Dương')
INSERT INTO Quan_Huyen VALUES(6206, 62, N'Huyện Vĩnh Tường')
INSERT INTO Quan_Huyen VALUES(6207, 62, N'Huyện Yên Lạc')
INSERT INTO Quan_Huyen VALUES(6208, 62, N'Thành phố Phúc Yên')
INSERT INTO Quan_Huyen VALUES(6209, 62, N'Thành phố Vĩnh Yên')
INSERT INTO Quan_Huyen VALUES(6301, 63, N'Huyện Lục Yên')
INSERT INTO Quan_Huyen VALUES(6302, 63, N'Huyện Mù Căng Chải')
INSERT INTO Quan_Huyen VALUES(6303, 63, N'Huyện Trạm Tấu')
INSERT INTO Quan_Huyen VALUES(6304, 63, N'Huyện Trấn Yên')
INSERT INTO Quan_Huyen VALUES(6305, 63, N'Huyện Văn Chấn')
INSERT INTO Quan_Huyen VALUES(6306, 63, N'Huyện Văn Yên')
INSERT INTO Quan_Huyen VALUES(6307, 63, N'Huyện Yên Bình')
INSERT INTO Quan_Huyen VALUES(6308, 63, N'Thành phố Yên Bái')
INSERT INTO Quan_Huyen VALUES(6309, 63, N'Thị xã Nghĩa Lộ')